# Generated by Django 3.1.3 on 2020-11-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangoo',
            name='c_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tangoo',
            name='s_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tangoo',
            name='supplement',
            field=models.TextField(blank=True, default=None),
        ),
    ]
