# Generated by Django 3.1.3 on 2020-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangoo', '0002_auto_20201119_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tangoo',
            name='supplement',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
