FROM node:14.3.0-buster

#COPY requirements.txt ${PWD}

#RUN npm rebuild node-sass
#RUN npm install -D sass-loader 
#npm install  -g @vue/cli && \

#RUN npm install -g npm 
#RUN npm install -g npm@7.1.0 && \
#    npm install -g @vue/cli && \
#    npm rebuild node-sass
#RUN npm install -g @vue/cli && \

WORKDIR /tmp/frontend
RUN npm install -g npm @vue/cli@3.5.2 && \
    npm install @vue/cli-plugin-babel 
    # npm i @vue/cli-service  
    # npm install @vue/cli-plugin-babel && \
    # npm install @vue/cli-plugin-eslint && \
    # npm install eslint && \
    # npm install -D eslint-plugin-vue && \
    # npm install --save @fortawesome/fontawesome-svg-core && \
    # npm install --save @fortawesome/free-solid-svg-icons && \
    # npm install --save @fortawesome/vue-fontawesome && \
    # npm install bootstrap && \
    # # npm install bootstrap/dist/css/bootstrap.min.css && \
    # npm install vue && \
    # npm install vue-router&& \
    # npm i @vue/cli-service  
    # npm install --save @vue/cli-service
    # npm rebuild node-sass && \
    # npm install @vue/babel-preset-app --save-dev && \

