version: '3.2'

services:
  backend:
    ports: 
      - "8000:8000"
    build: ./backend
    container_name: 'backend'
    volumes:
      - ./backend:/tmp/backend 
    stdin_open: true
    tty: true
    command: python manage.py runserver 0:8000
    depends_on:
      - db


  frontend:
    ports:
      - "8080:8080"
    build: ./frontend
    container_name: 'frontend'
    volumes:
      - ./frontend:/tmp/frontend
      - /tmp/frontend/node_modules/
    stdin_open: true
    tty: true
    command: >
      bash -c "cd ../frontend && npm run serve"

  db:
    image: postgres
    ports: 
       - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
